functions.php
header.php

Permite que plugins ou temas gerencie a tag ```<title>```. Funcionalidade implementada na versão 4.1 do WordPress.
Referencia http://codex.wordpress.org/Function_Reference/add_theme_support#Title_Tag

Added theme support 'title-tag'

---

404.php
archive.php
audio.php
author.php
category.php
image.php
index.php
page-sidebar.php
page.php
search.php
single.php

Conforme relatado na issue #250 o ID main estava duplicado em todas as páginas porque ele era chamado no header.php e em todos os outros arquivos de templates. Alterei o ID main para main-content em todos os arquivos de template para solucionar o problema.

issue #250

---

assets/js/latest-release.js
index.html

Galera, esse pull é o seguinte, atualmente o site está levando o download direto pro arquivo ZIP em desenvolvimento do branch master. Mas como hoje o odin já está usando tags como versões, faz mais sentido pegar a ultima release e essa ser o link de download no site, certo?
Como foi algo bem simples resolvi fazer até para me aventurar um pouco na API do GitHub, claro que se acharem que fica pesado adicionar mais uma requisição AJAX ao site (já existe a dos contribuidores) eu entendo totalmente. :)

download link using github api

---

core/assets/js/admin-custom-status.js
core/classes/class-metabox.php
core/classes/class-post-status.php
functions.php

Conforme PR  #266 tentei adaptar a classe ao standard do WP.
Usei meta tags para passar os argumentos para o JS, o wp_localize_script não funciona bem com várias instâncias, logo achei melhor fazer assim.
Abraços :)

Adicionando classe de Post Status

---

core/helpers.php

- Enabled parent for category crumbs on single and archives/category
pages.
- Fix post category parent without `<li>` tag.
- Correct name WooCommerce Shop page.
Fix to issue #208

Improved odin_breadcrumbs() with Woocommerce

---

core/classes/abstracts/abstract-front-end-form.php

Fix #317 upload problem if file is not required changing if($files) to if(count($files)

Fix #317 upload problem if file is not required

---

header.php

Different html elements should not be inline

better identation on header.php

---

core/helpers.php

When $origin_url is smaller than custom $width and $height, odin_get_image_url returns empty.

Improved odin_get_image_url return

---

core/assets/js/admin.js

Quando se tem 2 imagens e remove 1 delas, o código atual `attachmentIds = attachmentIds + attachmentId + ',';` acaba deixando no formato `id_imagem_1,`. Adicionei a mesma verificação de quando estamos criando a galeria, para que a primeira imagem seja adicionada à lista sem a vírgula.

Fix images list when deleting from plupload gallery

---

core/helpers.php

Check if WooCommerce is activated to avoid warnings when using 'product' as custom post type slug.

Check if WC is activated

---

core/classes/widgets/class-widget-like-box.php

Apenas adicionei um espaço antes do text-domain nestas funções, para ficar igual ao restante do código e facilitar o search/replace para alteração.

Espaço antes do text-domain [igual ao restante do código]

---

header.php

esc in url home and value search form

---

core/helpers.php

Notei que nos breadcrumbs a paginação só era exibida com parênteses envolvendo ela se fosse arquivo (conditional tag is_archive() ), ou seja, quando você possuía uma página com paginação a exibição não possuía espaço separando do nível anterior e nem os espaços.
Não entendi se tem algum propósito fazer aquela verificação, acredito que possa ser exibido com parênteses se tratando de arquivo ou não.

Adição e parênteses envolvendo a paginação no breadcrumb

---

core/classes/class-metabox.php

Não estavam utilizando $field['id'] mas sim o id da meta box. (Ocasionando o filtro ser aplicado para todos os campos da meta box)

Nome dos filtros de metabox field_before e field_after

---

core/classes/class-metabox.php

When assigning more than a CPT to a meta-box, using an Array(), I got 
```
Notice: Array to string conversion in class-metabox.php on line 48
Notice: Array to string conversion in class-metabox.php on line 50
```
the if(is_array()) and the forEach fixes this notice

fixes " Array to string conversion" notice

---

core/helpers.php

Parâmetro na query estava como 'showposts'. Tomei a liberdade de trocar uns nomes imensos de variáveis no foreach que acredito deixavam-no mais poluído do que didático.

Correção de showposts para posts_per_page na odin_related_posts

---

core/classes/class-metabox.php

Adicionando um filtro para substituir o caminho da imagem de placeholder para o field image.
```php
function meutema_odin_placeholder_path() {
return get_template_directory_uri() . '/vendor/odin/assets/images/placeholder.png';
}
add_filter('odin_placeholder_path', 'meutema_odin_placeholder_path');
```

Add filter placeholder image path

---

core/classes/class-term-meta.php
core/helpers.php
functions.php

Galera, só um adendo, desse jeito que eu fiz aqui eu não estou dando suporte para as versões antigas do WP, somente 4.4 pra cima. Acham que devo mudar isso? Adicionar condicionais verificando a versão?
No mais, essa classe ta funcionando com os campos antigos também (options API), mas sempre dando prioridade ao term meta, isso é, sempre que um campo for salvo da aqui pra frente, vai no term_meta e não no options api. Mas ainda deixei retornando valores do options, verificando por condicional se não existe no term meta e depois buscando no options.
Em breve podemos pensar num script pra migrar os campos antigos e arrancar de vez as funções antigas.
Abraços

Adicionando suporte as novas funções de term meta na classe de metabox para termos

---

core/classes/abstracts/abstract-front-end-form.php

Pull request to fix #163 and fix other little bug, `label` tags without `for` attribute.

Fixing issue #163

---

searchform.php

O searchform padrão fica meio quebrado no tema base, não seria melhor deixar o botão agrupado ao input? É uma sugestão boba, mas melhora um pouco a estética.
Antes:
Depois:

Fix searchform

---

functions.php
header.php
inc/template-tags.php

Adicionado **suporte para logo customizado** que entrou na [versão 4.5](https://wordpress.org/news/2016/04/coleman/) do WordPress :smile: 
Referencia: https://make.wordpress.org/core/2016/03/10/custom-logo/

Support custom logo

---

package.json
style.css

Algumas tags foram removidas na última versão, se não me engano: [Novas Tags](https://make.wordpress.org/themes/handbook/review/required/theme-tags/)
o npm estava retornando um erro no `package.json`, era apenas uma vírgula. Incluí ela aqui.

Changes in tags and missing comma

---

.gitignore

Não entendi muito bem porque a pasta src não está sendo versionada. O certo seria a pasta node_modules ter esse bloqueio.
Isso atrapalha um pouco quando faço o download do odin e inicio o projeto em um novo repo, a pasta src acaba não indo.
Abraços,

Versionar pasta src (GRUNT)

---

single.php

Volto a propor essa mudança nesse arquivo tomando como base a explicação abaixo.
O single.php atualmente possui o ID de navegação "main-content" sendo que o link de acesso rápido em header.php (linha 24) aponta para "content". 
O resultado é que sem a presença do ID correto a âncora não funcionará e assim o usuário que quiser acionar o Skip link na página interna do post vai ficar na mão.
O envelopamento do main dentro da div "primary" só ocorre no single.php e no video.php. Também já propus uma correção  para isso na pull #419 . Ao meu ver a mudança é válida. Não sendo gostaria de saber apenas o motivo pois em todos os demais arquivos de modelo abaixo descritos a div "primary" já foi removida.
index.php
page.php
page-sidebar.php
category.php
tag.php
image.php
404.php
search.php

Correção de Atalho de link rápido e padronização

---

core/assets/js/admin-custom-status.js

Olá pessoal, segue uma breve descrição das mudanças que fiz nesse arquivo.
**1:** 932a25ee319f53001848b51f43b0e90f0e4c82de Mudando o evento `load` para o `ready` (usando sintaxe `$( handler )`), visto que não precisamos esperar que todos os assets sejam carregados para executar essa função.
**2:** 69d382febe86811e6b16b8317edb7c53593c498f Um cache simples para evitar repetições de consulta ao DOM.
* [.ready()](http://api.jquery.com/ready/)
* [Avoid unnecessary DOM manipulations](https://browserdiet.com/#dont-touch-dom)

Post Status - Otimizações no JavaScript

---

src/README.md

Surgiu uma dúvida sobre o livereload [aqui](https://www.facebook.com/groups/wordpress.brasil/permalink/1226590524051583) no grupo do WP Brasil no Facebook.
Foi aí que reparei que não tínhamos isso descrito na documentação ainda.
**Obs:** Alguém pode me dar um help sobre como adicionar isso na página da Wiki sobre o Grunt?

Documentando o uso da task livereload

---

core/classes/abstracts/abstract-front-end-form.php
core/classes/class-contact-form.php

Debuguei aqui e tava retornando `Illegal offset tyepe` na linha 107 da *class_contact_form.php*,  geralmente causado por passar uma variável de uma array sem indicar um índice... Tudo que fiz foi indicar o índice `text` da array $label, necessário na construção dos dados submetidos para o corpo do email.
Depois da atualização do pr #163 a variável $label passou a retornar um array e não mais uma string.
Testei aqui e funfou de boa.. Acho que isso resolve as issues #397 e #430 .

Fix Contact form Bugs - labels and upload error ( #317, #397, #321 and #430 )

---

core/classes/class-bootstrap-nav.php

The strip tags removes any tag that could be on the title and solve SEO and acessibility issues.

Additing strip tags to the title of the menu link

---

core/helpers.php

A ideia é permitir que o usuário deixe a variável vazia para que a função use o atributo ALT da própria imagem.
Ainda será possível substituir a variável $alt caso necessário.
Essa mudança é especialmente útil em casos onde os campos de ALT já tiveram alteração no banco de dados para ganho de SEO e se deseja manter tais campos em loops de post.

$alt caso vazia, pega o atributo da imagem

---

inc/admin.php

O filtro login_headertitle foi depreciado na versão 5.2 do Core. Adicionei um teste lógico para utilizar o filtro login_headertext em seu lugar, suprimindo assim o aviso de depreciação.

Alteração do filtro depreciado login_headertitle

---

header.php

Indico a inclusão do hook wp_body_open() introduzido na versão 5.2.0 do Core WordPress por ser de grande utilidade para plugins.
Adicionei um teste de existência para manter o tema compatível com versões anteriores do Core.
Deixo abaixo algumas referências sobre esta função:
https://developer.wordpress.org/reference/functions/wp_body_open/
https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/
https://generatewp.com/wordpress-5-2-action-that-every-theme-should-use/

Adição do hook wp_body_open
