archive.php, audio.php, author.php, category.php, core/helpers.php, tag.php
Issue #230 Added 'the_post_navigation()' and 'the_archive_description()'
=> Added 'the_post_navigation()' and 'the_archive_description()' #230

src/Gruntfile.js
Correção de erro ao otimizar imagens.
=> Bug Fix: Unable to read ../assets/images/ file (Error code: EISDIR)

header.php
=> Removido hack IE 7 e 8 #243

inc/optimize.php
=> Corrigido title duplicado

assets/sass/_config.scss, src/Gruntfile.js, src/package.json
Como passei pelo mesmo problema relatado na issue #272, e reforçado pelo comentário do @claudiosmweb na issue #273, fiz a remoção do Compass e a implementação do LibSass.
=> Compass dependency removal. Inclusion of LibSass.

search.php
Estava inciando um freela hoje e achei isso aqui.
É algo simples, mas ta valendo ne.
Não sei se o section seria mais semântico que a div, mas as outras páginas estão como "div" também.
=> changes in closing tags

inc/woocommerce/functions.php
=> Corrige estrutura de tags WC

comments.php
Insert html5 comment form fields if is supported.
Simple fix for #303
=> html5 comment form fields

core/assets/js/admin.js
A variável contendo o id da imagem estava errada. ;)
=> Variable renamed.

header.php
=> remove default favicon if custom exists #337

src/Gruntfile.js
Recentemente utilizei o ftp-deploy e meu arquivo .ftppass foi enviado para o servidor. Nesta PR estou adicionando o arquivo nas exclusões do Grunfile.js.
=> Adding .ftppass file exclusions in FTP-deploy and rsync

core/helpers.php
Proposta de correção para a issue #359
=> Ajuste nos Breadcrumbs para Categorias aninhadas

core/helpers.php
Adicionado o exit na função debug para mostrar somente o conteúdo do echo e nada mais.
=> Optmize odin_debug function

core/classes/class-metabox.php
Testei aqui e o problema da issue está resolvido, qualquer coisa só comentar aqui =).
=> Fixing issue #124

tag.php
Seguindo a linha do que foi explicado no pull request #422  proponho a simplificação da marcação HTML
=> Padronização dos arquivos de template

README.md
Atualizado o Copyright para 2017
=> Atualizado o Copyright

inc/comments-loop.php
`odin_comment_loop` to `odin_comments_loop`
=> typo on comments-loop.php

audio.php, core/classes/class-bootstrap-nav.php, core/helpers.php, inc/woocommerce/template-tags.php
Alguns conteúdos entre tags HTML estavam sendo retornados com a função esc_attr. Alterei para que utilizassem a função esc_html.
=> Update to escape content correctly

functions.php
Ao invés de adicionar o Jquery diretamente, colocar ele como dependência dos script que o utilizam.
=> Add jQuery as dependency

README.md, package-lock.json, package.json
olá pessoal!
Fui pegar o beta pra testar e começar a estudar alguns updates, e me deparei com alguns erros concernentes à SO (Win10) e versão do node (v10...) que uso, além da necessidade de ter que instalar o compilador C++ no windows pra poder rodar o `npm install`.
Então adicionei algumas migalhas para o pobre usuário do Windows (como eu) não desanimar logo de cara.
*Se bem que ninguém vai querer pegar esse branch logo de né!? .. mas tá aí!*
=> Cross platform compatibility

header.php
=> Adição do hook wp_body_open() no Tema
